### ISSUE TITLE
404 on https://ci.xephi.fr/plugin/repository/everything/

### ISSUE THREAD

**Issue by Bucky420** [timvisee/yaml-wrapper#4]
is this just me ?

**Comment by timvisee** [comment]
It's hosted on a 3rd party repository, which I don't have control over myself.

It's currently available here:
https://repo.codemc.org/#browse/browse:maven-releases:com%2Ftimvisee%2Fyamlwrapper

I might host the package on GitLab soon, to make sure the repository stays live.

**Comment by Bucky420** [comment]
ty so much <3
